import type { InferInsertModel } from "drizzle-orm";
import { corridorMilestoneTemplates } from "../schema";

type TemplateInsert = InferInsertModel<typeof corridorMilestoneTemplates>;

const fclMilestones: Omit<TemplateInsert, "id" | "createdAt">[] = [
  {
    corridorType: "fcl",
    milestoneKey: "BOOKING_CONFIRMED",
    milestoneLabel: "Booking Confirmed",
    description: "Carrier has confirmed the booking for the container shipment",
    milestoneOrder: 1,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "fcl",
    milestoneKey: "EMPTY_CONTAINER_REQUESTED",
    milestoneLabel: "Empty Container Requested",
    description: "Request placed for empty container equipment at designated depot",
    milestoneOrder: 2,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 48,
  },
  {
    corridorType: "fcl",
    milestoneKey: "CONTAINER_RELEASED",
    milestoneLabel: "Container Released",
    description: "Empty container has been released from the depot",
    milestoneOrder: 3,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "fcl",
    milestoneKey: "CONTAINER_PICKED_UP",
    milestoneLabel: "Container Picked Up",
    description: "Empty container picked up from depot by trucking provider",
    milestoneOrder: 4,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 8,
  },
  {
    corridorType: "fcl",
    milestoneKey: "CONTAINER_STUFFED",
    milestoneLabel: "Container Stuffed",
    description: "Cargo has been loaded and stuffed into the container",
    milestoneOrder: 5,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "fcl",
    milestoneKey: "CONTAINER_SEALED",
    milestoneLabel: "Container Sealed",
    description: "Container sealed with shipping line seal number recorded",
    milestoneOrder: 6,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "fcl",
    milestoneKey: "DELIVERED_TO_PORT",
    milestoneLabel: "Delivered to Port",
    description: "Full container delivered to port terminal for export",
    milestoneOrder: 7,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "fcl",
    milestoneKey: "EXPORT_CUSTOMS_FILING",
    milestoneLabel: "Export Customs Filing",
    description: "Export customs declaration filed with customs authority",
    milestoneOrder: 8,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "fcl",
    milestoneKey: "EXPORT_CUSTOMS_CLEARED",
    milestoneLabel: "Export Customs Cleared",
    description: "Export customs clearance obtained, container cleared for loading",
    milestoneOrder: 9,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 12,
  },
  {
    corridorType: "fcl",
    milestoneKey: "VESSEL_LOADED",
    milestoneLabel: "Vessel Loaded",
    description: "Container loaded onto the ocean vessel at port of loading",
    milestoneOrder: 10,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "fcl",
    milestoneKey: "VESSEL_DEPARTED_POL",
    milestoneLabel: "Vessel Departed POL",
    description: "Vessel has departed the port of loading",
    milestoneOrder: 11,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 336,
  },
  {
    corridorType: "fcl",
    milestoneKey: "TRANSSHIPMENT",
    milestoneLabel: "Transshipment",
    description: "Container transferred at intermediate port to connecting vessel",
    milestoneOrder: 12,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 72,
  },
  {
    corridorType: "fcl",
    milestoneKey: "VESSEL_ARRIVED_POD",
    milestoneLabel: "Vessel Arrived POD",
    description: "Vessel has arrived at the port of discharge",
    milestoneOrder: 13,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 48,
  },
  {
    corridorType: "fcl",
    milestoneKey: "IMPORT_CUSTOMS_FILING",
    milestoneLabel: "Import Customs Filing",
    description: "Import customs declaration filed with destination customs authority",
    milestoneOrder: 14,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 48,
  },
  {
    corridorType: "fcl",
    milestoneKey: "IMPORT_CUSTOMS_CLEARED",
    milestoneLabel: "Import Customs Cleared",
    description: "Import customs clearance obtained, container released from port",
    milestoneOrder: 15,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "fcl",
    milestoneKey: "CONTAINER_DISCHARGED",
    milestoneLabel: "Container Discharged",
    description: "Container discharged from vessel and grounded at terminal",
    milestoneOrder: 16,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "fcl",
    milestoneKey: "OUT_FOR_DELIVERY",
    milestoneLabel: "Out for Delivery",
    description: "Container picked up from terminal, en route to consignee",
    milestoneOrder: 17,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 12,
  },
  {
    corridorType: "fcl",
    milestoneKey: "CONTAINER_DELIVERED",
    milestoneLabel: "Container Delivered",
    description: "Full container delivered to consignee's facility",
    milestoneOrder: 18,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 8,
  },
  {
    corridorType: "fcl",
    milestoneKey: "CONTAINER_EMPTY_RETURNED",
    milestoneLabel: "Empty Container Returned",
    description: "Empty container returned to designated depot or terminal",
    milestoneOrder: 19,
    defaultNotificationEnabled: false,
    estimatedDurationHours: null,
  },
];

const ltlMilestones: Omit<TemplateInsert, "id" | "createdAt">[] = [
  {
    corridorType: "ltl",
    milestoneKey: "PICKUP_SCHEDULED",
    milestoneLabel: "Pickup Scheduled",
    description: "Pickup appointment scheduled with carrier for LTL freight",
    milestoneOrder: 1,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "ltl",
    milestoneKey: "PICKUP_CONFIRMED",
    milestoneLabel: "Pickup Confirmed",
    description: "Carrier has confirmed the pickup assignment",
    milestoneOrder: 2,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 8,
  },
  {
    corridorType: "ltl",
    milestoneKey: "PICKED_UP_FROM_SHIPPER",
    milestoneLabel: "Picked Up from Shipper",
    description: "Freight has been picked up from shipper's location",
    milestoneOrder: 3,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "ltl",
    milestoneKey: "ARRIVED_ORIGIN_TERMINAL",
    milestoneLabel: "Arrived at Origin Terminal",
    description: "Freight received at carrier's origin terminal / service center",
    milestoneOrder: 4,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "ltl",
    milestoneKey: "FREIGHT_SORTED",
    milestoneLabel: "Freight Sorted",
    description: "Freight sorted and staged for linehaul at origin terminal",
    milestoneOrder: 5,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 8,
  },
  {
    corridorType: "ltl",
    milestoneKey: "LOADED_ON_LINEHAUL",
    milestoneLabel: "Loaded on Linehaul",
    description: "Freight loaded onto linehaul trailer for long-haul transport",
    milestoneOrder: 6,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 48,
  },
  {
    corridorType: "ltl",
    milestoneKey: "IN_TRANSIT_LINEHAUL",
    milestoneLabel: "In Transit — Linehaul",
    description: "Freight in transit on linehaul between terminals",
    milestoneOrder: 7,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "ltl",
    milestoneKey: "ARRIVED_BREAKBULK",
    milestoneLabel: "Arrived at Breakbulk",
    description: "Freight arrived at intermediate breakbulk terminal",
    milestoneOrder: 8,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 8,
  },
  {
    corridorType: "ltl",
    milestoneKey: "CROSS_DOCKED",
    milestoneLabel: "Cross-docked",
    description: "Freight transferred to destination-bound trailer at breakbulk",
    milestoneOrder: 9,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 12,
  },
  {
    corridorType: "ltl",
    milestoneKey: "ARRIVED_DEST_TERMINAL",
    milestoneLabel: "Arrived at Destination Terminal",
    description: "Freight arrived at destination service center",
    milestoneOrder: 10,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 8,
  },
  {
    corridorType: "ltl",
    milestoneKey: "DEST_SORTED",
    milestoneLabel: "Destination Sorted",
    description: "Freight sorted for delivery route at destination terminal",
    milestoneOrder: 11,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "ltl",
    milestoneKey: "LOADED_DELIVERY_TRUCK",
    milestoneLabel: "Loaded on Delivery Truck",
    description: "Freight loaded onto local delivery truck",
    milestoneOrder: 12,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "ltl",
    milestoneKey: "OUT_FOR_DELIVERY",
    milestoneLabel: "Out for Delivery",
    description: "Freight out for final delivery to consignee",
    milestoneOrder: 13,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 8,
  },
  {
    corridorType: "ltl",
    milestoneKey: "DELIVERY_ATTEMPTED",
    milestoneLabel: "Delivery Attempted",
    description: "Delivery attempted but consignee unavailable — rescheduling",
    milestoneOrder: 14,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 24,
  },
  {
    corridorType: "ltl",
    milestoneKey: "DELIVERED",
    milestoneLabel: "Delivered",
    description: "Freight delivered to consignee, proof of delivery obtained",
    milestoneOrder: 15,
    defaultNotificationEnabled: true,
    estimatedDurationHours: null,
  },
  {
    corridorType: "ltl",
    milestoneKey: "POD_AVAILABLE",
    milestoneLabel: "POD Available",
    description: "Signed proof of delivery document available for download",
    milestoneOrder: 16,
    defaultNotificationEnabled: false,
    estimatedDurationHours: null,
  },
  {
    corridorType: "ltl",
    milestoneKey: "EXCEPTION_DAMAGED",
    milestoneLabel: "Exception — Damaged",
    description: "Freight reported damaged during transit",
    milestoneOrder: 99,
    defaultNotificationEnabled: true,
    estimatedDurationHours: null,
  },
  {
    corridorType: "ltl",
    milestoneKey: "EXCEPTION_LOST",
    milestoneLabel: "Exception — Lost",
    description: "Freight reported lost or missing during transit",
    milestoneOrder: 100,
    defaultNotificationEnabled: true,
    estimatedDurationHours: null,
  },
];

const drayageMilestones: Omit<TemplateInsert, "id" | "createdAt">[] = [
  {
    corridorType: "drayage",
    milestoneKey: "ORDER_RECEIVED",
    milestoneLabel: "Order Received",
    description: "Drayage order received and entered into the system",
    milestoneOrder: 1,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "drayage",
    milestoneKey: "DISPATCH_ASSIGNED",
    milestoneLabel: "Dispatch Assigned",
    description: "Order dispatched to drayage carrier or driver pool",
    milestoneOrder: 2,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 2,
  },
  {
    corridorType: "drayage",
    milestoneKey: "DRIVER_ASSIGNED",
    milestoneLabel: "Driver Assigned",
    description: "Specific driver and truck assigned to the move",
    milestoneOrder: 3,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 2,
  },
  {
    corridorType: "drayage",
    milestoneKey: "CHASSIS_SECURED",
    milestoneLabel: "Chassis Secured",
    description: "Chassis obtained from pool or rental provider",
    milestoneOrder: 4,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 2,
  },
  {
    corridorType: "drayage",
    milestoneKey: "CONTAINER_PICKUP_PORT",
    milestoneLabel: "Container Pick-up at Port",
    description: "Container picked up from port or rail terminal",
    milestoneOrder: 5,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "drayage",
    milestoneKey: "IN_TRANSIT_TO_WAREHOUSE",
    milestoneLabel: "In Transit to Warehouse",
    description: "Container en route from port to warehouse or delivery point",
    milestoneOrder: 6,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "drayage",
    milestoneKey: "ARRIVED_AT_WAREHOUSE",
    milestoneLabel: "Arrived at Warehouse",
    description: "Container arrived at destination warehouse or facility",
    milestoneOrder: 7,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "drayage",
    milestoneKey: "UNLOADING_STARTED",
    milestoneLabel: "Unloading Started",
    description: "Container unloading in progress at warehouse",
    milestoneOrder: 8,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "drayage",
    milestoneKey: "UNLOADING_COMPLETE",
    milestoneLabel: "Unloading Complete",
    description: "All cargo unloaded from container",
    milestoneOrder: 9,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 2,
  },
  {
    corridorType: "drayage",
    milestoneKey: "CONTAINER_AVAILABLE_RETURN",
    milestoneLabel: "Container Available for Return",
    description: "Empty container ready for return to port or depot",
    milestoneOrder: 10,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "drayage",
    milestoneKey: "IN_TRANSIT_TO_PORT",
    milestoneLabel: "Returning to Port",
    description: "Empty container en route back to port or depot",
    milestoneOrder: 11,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 4,
  },
  {
    corridorType: "drayage",
    milestoneKey: "CONTAINER_RETURNED",
    milestoneLabel: "Container Returned to Port",
    description: "Empty container returned and checked in at port or depot",
    milestoneOrder: 12,
    defaultNotificationEnabled: true,
    estimatedDurationHours: 2,
  },
  {
    corridorType: "drayage",
    milestoneKey: "CHASSIS_RETURNED",
    milestoneLabel: "Chassis Returned",
    description: "Chassis returned to pool or rental provider",
    milestoneOrder: 13,
    defaultNotificationEnabled: false,
    estimatedDurationHours: 2,
  },
  {
    corridorType: "drayage",
    milestoneKey: "ORDER_COMPLETE",
    milestoneLabel: "Order Complete",
    description: "All drayage moves completed and equipment returned",
    milestoneOrder: 14,
    defaultNotificationEnabled: true,
    estimatedDurationHours: null,
  },
  {
    corridorType: "drayage",
    milestoneKey: "INVOICE_GENERATED",
    milestoneLabel: "Invoice Generated",
    description: "Invoice generated for completed drayage service",
    milestoneOrder: 15,
    defaultNotificationEnabled: false,
    estimatedDurationHours: null,
  },
  {
    corridorType: "drayage",
    milestoneKey: "EXCEPTION_CONTAINER_UNAVAILABLE",
    milestoneLabel: "Exception — Container Unavailable",
    description: "Container not yet available for pick-up at port",
    milestoneOrder: 99,
    defaultNotificationEnabled: true,
    estimatedDurationHours: null,
  },
  {
    corridorType: "drayage",
    milestoneKey: "EXCEPTION_CHASSIS_SHORTAGE",
    milestoneLabel: "Exception — Chassis Shortage",
    description: "No chassis available at port or pool — delayed assignment",
    milestoneOrder: 100,
    defaultNotificationEnabled: true,
    estimatedDurationHours: null,
  },
  {
    corridorType: "drayage",
    milestoneKey: "EXCEPTION_PORT_CONGESTION",
    milestoneLabel: "Exception — Port Congestion",
    description: "Port congestion causing extended wait times for container pickup",
    milestoneOrder: 101,
    defaultNotificationEnabled: true,
    estimatedDurationHours: null,
  },
];

export const allMilestoneTemplates = [
  ...fclMilestones,
  ...ltlMilestones,
  ...drayageMilestones,
];

export function getSeedData(): Omit<TemplateInsert, "id" | "createdAt">[] {
  return allMilestoneTemplates;
}
